# Generated by Django 4.1 on 2024-10-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название')),
                ('model', models.CharField(max_length=50, verbose_name='Модель ИИ')),
                ('max_token', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Мод ИИ',
                'verbose_name_plural': 'Моды ИИ',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000, verbose_name='Текст промпта')),
                ('name', models.CharField(max_length=50, verbose_name='Название промпта')),
            ],
            options={
                'verbose_name': 'Промпт',
                'verbose_name_plural': 'Промпты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('message_context', models.JSONField(verbose_name='История переписки пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='UserMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_amount', models.IntegerField(verbose_name='Количество запросов')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mode', to='bot.mode', verbose_name='Мод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mode', to='bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Юзер-Мод',
                'verbose_name_plural': 'Юзер-Моды',
            },
        ),
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referal', to='bot.user', verbose_name='Пригласитель')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералки',
            },
        ),
    ]
