# Generated by Django 4.1 on 2024-12-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='is_image',
            field=models.BooleanField(default=False, verbose_name='Режим для генерации картинок?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Реферальный ID пользователя'),
        ),
    ]
