# Generated by Django 4.1 on 2024-10-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='max_token',
            field=models.IntegerField(verbose_name='Максимальное кол запросов'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='Фото для оформления покупки'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость мода'),
        ),
    ]
