# Generated by Django 4.1 on 2024-12-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermode',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mode', to='bot.mode', verbose_name='Режим'),
        ),
        migrations.AlterField(
            model_name='usermode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mode', to='bot.user', verbose_name='Юзер'),
        ),
    ]
