# Generated by Django 4.1 on 2024-12-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_plan',
            field=models.BooleanField(default=False),
        ),
    ]
