# Generated by Django 4.1 on 2024-12-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_has_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mode',
            field=models.CharField(blank=True, default='base', help_text='base по умолчанию', max_length=35, null=True, verbose_name='Режим пользователя base/doc'),
        ),
    ]
